### ISSUE TITLE
A better default onUnhandledRejection handler

### ISSUE THREAD

**Issue by dracupid** [ysmood/yaku#1]
console.trace is not a good enough way to show stack trace. Also, uglified code make it pretty difficult to debug.

Unhandled rejection Error: [TypeError: Cannot read property 'value' of undefined]
Trace
  at Function.t.onUnhandledRejection (/usr/local/lib/node_modules/nokit/node_modules/nofs/node_modules/yaku/dist/yaku.js:6:822)
  at /usr/local/lib/node_modules/nokit/node_modules/nofs/node_modules/yaku/dist/yaku.js:6:2168
  at r (/usr/local/lib/node_modules/nokit/node_modules/nofs/node_modules/yaku/dist/yaku.js:6:1171)
  at process._tickCallback (node.js:442:13)

**Comment by ysmood** [comment]
No, you should read this article [Blackbox JavaScript Source Files][], your paste code should be invisible in the v8. The stack trace of a basic library is not necessary, you never have to read the code of a Promise library. For example, if you throw an error in Native Promise, the stack trace will only shows `[native code]`.

Blackbox JavaScript Source Files: https://developer.chrome.com/devtools/docs/blackboxing

**Comment by ysmood** [comment]
But still, I can do some string hack about it.

**Comment by dracupid** [comment]
Print the stack of the error it caught should be better than console.trace, a long stack trace helper may be not that necessary for this case.

**Comment by dracupid** [comment]
I admit that I should not care the stack detail in library. I just want to show my suprise when I saw the code. 😅

**Comment by ysmood** [comment]
No, without long stack trace you cannot. The native promise also show where the error came from without long stack trace enabled.

**Comment by ysmood** [comment]
Goto #3
