### ISSUE TITLE
Promise.any?

### ISSUE THREAD

**Issue by andrewwakeling** [ysmood/yaku#15]
It's desirable for me to have Promise.any. (i.e. If any promise resolves, then resolve).

Is it possible to create this method using the existing methods in Yaku? (e.g. I could do something similar to https://github.com/andyjansson/promise-any/blob/master/index.js ).

Is this a good idea? or should I wait for this functionality to appear in Yaku?

**Comment by ysmood** [comment]
Do you mean "Promise.race"? Yaku supports it by default.

**Comment by andrewwakeling** [comment]
It's different.

Promise.any will resolve if any of the supplied promises resolve. It will only reject, if all of the promises reject.

**Comment by ysmood** [comment]
Well, I understand. How about add it to the yuku's utils namespace?

**Comment by ysmood** [comment]
https://github.com/ysmood/yaku/commit/7c7de32390d23161551f5002e35c9ecb1de168f2

How about this?

**Comment by ysmood** [comment]
If you are interested in the ef23611, please make pull request for and fix the TODOs.

**Comment by benjamingr** [comment]
`Promise.race` is very broken in that it will create a promise that pends forever with `Promise.race([])` which is hard to debug.

In addition, if one promise rejects all the other rejections will go unhandled and unreported with `.race`, with `.any` we have the chance to return an iteration over all rejections (a promise for one, anyway).

Basically, you have a chance to provide a better API with `.any`.

**Comment by ysmood** [comment]
Added, and it supports [iteratable](iteratable) by default.

Now all the function of yaku that handles array supports [iteratable](iteratable).

[iterable]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols

**Comment by andrewwakeling** [comment]
Thanks for implementing this so promptly! :+1:
