### ISSUE TITLE
Docs about utilities, and utilities

### ISSUE THREAD

**Issue by benjamingr** [ysmood/yaku#19]
Hey, the docs say that the library does not offer things like `.done`, but it appears it just exposes a (differently named) `.end` instead. 

I warmly recommend the following:

 - Remove `.defer`, deferreds are super problematic anyway, they were decided against in the official API for the Zalgo problem they cause. 
 - Remove `.end`, you have unhandled rejection detection already - that's better anyway. 
 - Don't expose `.isPromise`, that encourages (in my experience) users to rely on it instead of `Promise.resolve`ing results.
 - Move `source` to another unrelated repo, it is practically a mini [observable](https://github.com/zenparsing/es-observable). It's worth documenting separately. 
 - Don't show examples in the docs that throw non-Errors as that breaks stack traces, as a library that implements long stack traces I assume you care about that.

**Comment by ysmood** [comment]
The `end` is very special, it returns a promise that never resolve. `done` function is like `then` but doesn't return a promise.

**Comment by ysmood** [comment]
Thanks for your advise, I will add `deprecate` warning for `Defer`, `isPromise`.

**Comment by ysmood** [comment]
I'm already working on `Observable`, see the branch: https://github.com/ysmood/yaku/tree/observable

I will move it to a separate project when it's api is stable.

**Comment by ysmood** [comment]
> Don't show examples in the docs that throw non-Errors as that breaks stack traces, as a library that implements long stack traces I assume you care about that.

Which example you mean?

**Comment by benjamingr** [comment]
For example: `Promise.reject("reason")`

**Comment by ysmood** [comment]
fixed bee466240a4e
