### ISSUE TITLE
Support global unhandled rejection detection events

### ISSUE THREAD

**Issue by benjamingr** [ysmood/yaku#20]
Basically https://gist.github.com/benjamingr/0237932cee84712951a2 

Most promise libraries and native promises in NodeJS support the global rejection events, these events in NodeJS allow code using multiple promise libraries and native promises in the same project to handle rejecitons globally and uniformally throughout the application and to provide a useful hook. 

It also makes switching libraries simpler. 

It would be great if Yaku could support it, I don't mind writing the PR but I think that you already know how to :)

**Comment by ysmood** [comment]
Yaku will not touch any global API, instead I will leave enought APIs to let user achieve it easily. For example, you can use utils.globalizeUnhandledRejection() to do it.

**Comment by benjamingr** [comment]
As long as you realize that this is a deviation from native promises which means Yaku isn't a drop in replacement for native promises be my guest.

**Comment by ysmood** [comment]
You may be right. I will rethink about it.

**Comment by ysmood** [comment]
fixed a3de83ee5d09
