### ISSUE TITLE
instance constructor is not Promise

### ISSUE THREAD

**Issue by kentor** [ysmood/yaku#22]
I'm using `promise.prototype.finally` to add the `finally` functionaity to Promises, but that depends on the promise's `constructor` to be `Promise`. Currently the constructor is `Object`.

```js
> (new Promise(function() {})).constructor
Object() { [native code] }
```

**Comment by ysmood** [comment]
Sorry for so late. I'm on a vacation lately.

**Comment by kentor** [comment]
Thanks :+1:
