### ISSUE TITLE
Incorrect testcases

### ISSUE THREAD

**Issue by hax** [ysmood/yaku#29]
See my comments in https://github.com/ysmood/yaku/commit/0383fa02e711eec363b85c299a45004986ecb249

**Comment by ysmood** [comment]
But I only test it against Node v5.0 and above, we don't have to skip it. The test result is based on Node v5.6. Don't worry about the `Symbol`, the comparison graph is based on Node v5.0+, and will always use the lastest version of Node.

**Comment by ysmood** [comment]
The readme is updated. You lib passed all tests. Thanks for your report.

**Comment by hax** [comment]
Test case "subclass PromiseCapability promise.then TypeError" is still incorrect. It should not throw error. To throw error you need to specify `Symbol.species` for fake constructor 😈

**Comment by ysmood** [comment]
But, I read the https://tc39.github.io/ecma262/#sec-newpromisecapability

> If IsCallable(promiseCapability.[[Resolve]]) is false, throw a TypeError exception.

The newly created `promiseCapability` should have a `resolve` handler.

**Comment by hax** [comment]
The test case call `promise.then(function () {})` with `promise.constructor = function () {}`.

See [25.4.5.3 Promise.prototype.then](https://tc39.github.io/ecma262/#sec-promise.prototype.then)
> 3 . Let C be ? SpeciesConstructor(promise, %Promise%).

Step 3 passes `promise` with `%Promise%` (the original Promise constructor) as `defaultConstructor`

See [7.3.20 SpeciesConstructor](https://tc39.github.io/ecma262/#sec-speciesconstructor)
> 1. Assert: Type(O) is Object.
> 2. Let C be ? Get(O, "constructor").
> 3. If C is undefined, return defaultConstructor.
> 4. If Type(C) is not Object, throw a TypeError exception.
> 5. Let S be ? Get(C, @@species).
> 6. If S is either undefined or null, return defaultConstructor.
> 7. If IsConstructor(S) is true, return S.
> 8. Throw a TypeError exception.

Step 2: C = `function () {}`
Step 5: S = `undefined`
Step 6: return `%Promise%`

Then `NewPromiseCapability` is called with original Promise constructor.

**Comment by ysmood** [comment]
You are right, I added a global `Symbol.species` to make the test possible: https://github.com/ysmood/yaku/commit/ccd5a01646641625d53abac2950ea26c2c190c22#diff-e2686e2925145c11799d638b2f4706dcR8

But I don't why `my-promise` still has 1 failure: 

```
$ npm run no -- test-basic -s my-promise

> yaku@0.15.8 no /Users/ys/cradle/yaku
> no "test-basic" "-s" "my-promise"

# /Users/ys/cradle/yaku/nofile.js
[2016-04-27 17:36:51] Task Start >> [test-basic] test basic specs tests 0ms
junit cli > o basic - subclass PromiseCapability promise.then (7ms)
junit cli > o basic - resolve (25ms)
junit cli > o basic - resolve promise like value (24ms)
junit cli > o basic - constructor throw (24ms)
junit cli > o basic - resolve static (24ms)
junit cli > o basic - resolve promise (24ms)
junit cli > o basic - reject (25ms)
junit cli > o basic - catch (25ms)
junit cli > o basic - all with empty (24ms)
junit cli > o basic - all with null (24ms)
junit cli > o basic - all with array like (24ms)
junit cli > o basic - all with custom Symbol.iterator (23ms)
junit cli > o basic - all with iterator like (22ms)
junit cli > o basic - all with iterator like, iteration error (22ms)
junit cli > o basic - all with iterator like, resolve error (22ms)
junit cli > o basic - race with null (22ms)
junit cli > o basic - race with custom Symbol.iterator (22ms)
junit cli > o basic - race with iterator like (22ms)
junit cli > o basic - race with iterator like, iteration error (22ms)
junit cli > o basic - race with iterator like, resolve error (22ms)
junit cli > x basic - subclass (21ms)
  
  <<<<<<< actual
  [ 'subclass',
    undefined,
    'subclass',
    undefined,
    'subclass',
    true,
    true,
    5,
    6 ]
  =======
  [ 'subclass',
    'subclass',
    'subclass',
    'subclass',
    'subclass',
    true,
    true,
    5,
    6 ]
  >>>>>>> expected
  
  Error: Assertion
  

junit cli > o basic - subclass PromiseCapability fake constructor promise.then (20ms)
junit cli > o basic - race (24ms)
junit cli > o basic - all (27ms)
junit cli > o basic - chain (28ms)
junit cli > o basic - race with empty should never resolve (33ms)
junit cli > o basic - resolve order (104ms)
junit cli > tested 27 / 27
junit cli > passed 26
junit cli > failed 1
```

**Comment by hax** [comment]
I will check it later.
