### ISSUE TITLE
`finally` is now stage 2

### ISSUE THREAD

**Issue by JakeChampion** [ysmood/yaku#35]
When do we consider adding `finally` to `yaku`?
https://github.com/tc39/proposal-promise-finally

From `yaku` readme:

> - Will Yaku implement done, finally, etc?
> 
> > No. All non-ES6 APIs are only implemented for debugging and testing, which means when you remove Yaku, everything should work well with ES6 native promise.

**Comment by ysmood** [comment]
Thanks, I'll implement it ASAP.

**Comment by ysmood** [comment]
ES6 is locked, so it should be a part of ES7 or somehow. I'm sorry that I'm a little outdated.

**Comment by JakeChampion** [comment]
It's not in ES2016/ES7, only two Math methods were added to ES2016/ES7. It will hopefully enter Stage 3 at some point this year.

Criteria to move to Stage 3:
- Complete spec text
- Designated reviewers have signed off on the current spec text
- The ECMAScript editor has signed off on the current spec text

It is up to you where to implement it. I imagine people would be confused if they had to install Yaku and a Yaku plugin to get ES-Promises working.

**Comment by ysmood** [comment]
Right, it should be inside the core.

**Comment by JakeChampion** [comment]
@ysmood Do you need some help with this feature at all?

**Comment by ysmood** [comment]
Yes, I need some help. The performance is my main concern.

**Comment by ysmood** [comment]
The two extra closure makes me headache. I may merge the finally branch if I have time to add more test cases.

**Comment by ysmood** [comment]
@JakeChampion I published the version v0.17.0 with the newly added `finally` support. Hope its not too late.

**Comment by JakeChampion** [comment]
Thanks!

**Comment by JakeChampion** [comment]
Looks to fail some tests in these browsers:
```
 • ie/11
 • ie/10
 • ie/9
 • ie/8
 • android/4.4
```

**Comment by ysmood** [comment]
May I see the error information?

**Comment by JakeChampion** [comment]
Rerunning the test suite now as I had some configuration errors which reported lots of false positives. Apologies if it turns out everything is working.

**Comment by JakeChampion** [comment]
Tests pass on all except IE8 which seems to hang

**Comment by ysmood** [comment]
I will double check it later.
