### ISSUE TITLE
`then` memory leak

### ISSUE THREAD

**Issue by ysmood** [ysmood/yaku#37]
If we call a promise's `then` method multiple times, it may potentially cause memory leak:

``` js
var p = Promise.resolve();

p.then(function () {});
p.then(function () {});
p.then(function () {});
p.then(function () {});
p.then(function () {});

process.on('exit', () => {
    p = null;
});
```

If we don't release variable `p`, its children promises will stay in memory even after `p` and all the children are settled. What we should do with this situation is not specified in the ES6 yet.

I think we should cut off the link between the parent and child immediately after the child is settled.

**Comment by JakeChampion** [comment]
Have you posted about this on the es-discuss@mozilla.org mailing list?

**Comment by ysmood** [comment]
No, but I think it's a common issue of Promise libs
2016年11月18日(金) 23:43 Jake Champion <notifications@github.com>:
