### ISSUE TITLE
Can't register global unhandled rejection 

### ISSUE THREAD

**Issue by derobo** [ysmood/yaku#44]
i try to add a handler for all  unhandled rejection:
window.onunhandledrejection = ({ reason, promise }) => { console.log('help');};
Promise.reject(new Error("ERR"));

The only output i can see is the default 'Potentially unhandled rejection [1] Error: ERR'. 
Is it a bug or am i using it wrong?

**Comment by ysmood** [comment]
Are you sure you are using Yaku? If you use the native Promise, you should get what you seen.
