### ISSUE TITLE
Does not work on UC Browser

### ISSUE THREAD

**Issue by JoyceBabu** [ysmood/yaku#45]
The following code is not working in UC Browser, because `this` is undefined inside an IIFE in UC Browser.

```
function(module, exports, __webpack_require__) {

	/* WEBPACK VAR INJECTION */(function(global) {var Yaku = __webpack_require__(/*! ./yaku */ 80);

	try {
	    global.Promise = Yaku;
	    window.Promise = Yaku;
	} catch (err) {
	    null;
	}
	/* WEBPACK VAR INJECTION */}.call(exports, (function() { return this; }())))

/***/ }
```

**Comment by ysmood** [comment]
I think this may be a bug of webpack, not Yaku?

**Comment by JoyceBabu** [comment]
@ysmood I believe it is actually a bug with UC Browser, as all other browsers are working correctly.

I have opened an issue with webpack https://github.com/webpack/webpack/issues/4743

Since Yaku is bundled as the default polyfill in polyfill.io, the service is currently broken for UC Browser users. According to StatsCounter, UC Browser has a global browser market share of 8.75%. According to some reports, in india it is as high as 50%. 28% of our traffic is from UC Browser.

Until it is fixed in webpack, can you please add a work around? `(global||{}).Promise` would look ugly, but would greatly increase the browser compability of the polyfill.

**Comment by ysmood** [comment]
`(global||{}).Promise` added, and new version was published, good luck.

**Comment by JoyceBabu** [comment]
Thank you. It is now working on UC Browser.

**Comment by JoyceBabu** [comment]
I tried with building the polyfill with webpack 2, as per advice at https://github.com/webpack/webpack/issues/4743 

The issue is fixed in webpack 2. The above fix can be removed when upgrading to webpack 2.

**Comment by ysmood** [comment]
Thanks for your feedback.

**Comment by JoyceBabu** [comment]
@ysmood Do you have plans to update to WebPack 2? If not, shall I create the PR for  https://github.com/Financial-Times/polyfill-service?

**Comment by ysmood** [comment]
851df7fed59795110ff1890cfefb9e50f9d78633

Updated and new version published, if you have any problem, please let me know.

**Comment by JoyceBabu** [comment]
The updated plugin is working correctly on UC Browser. Thank you.
