### ISSUE TITLE
incorrect behavior with unhandledrejection events

### ISSUE THREAD

**Issue by rtsao** [ysmood/yaku#46]
Per https://github.com/ysmood/yaku/blob/master/docs/debugHelperComparison.md#better-unhandled-error, Yaku will **not** fire an `unhandledrejection` event in this case:

```js
p0 = Yaku.resolve().then(function () {
    abc()
})
p1 = p0.then(function () {})
p2 = p0.then(function () {})
p3 = p0.catch(function () {})
```

From my understanding, this is incorrect behavior. `p1` and `p2` are new promises that have unhandled rejections.

I think the following should happen:
```js
window.onunhandledrejection = ({promise}) => { 
  console.log('window.onunhandledrejection: p' + promises.indexOf(promise));
}
p0 = Yaku.resolve().then(function () {
    abc()
})
p1 = p0.then(function () {})
p2 = p0.then(function () {})
p3 = p0.catch(function () {})
promises = [p0, p1, p2, p3]

// should log 'unhandledrejection: p1'
// should log 'unhandledrejection: p2'
```

I believe Chrome actually implements the spec correctly.

**Comment by ysmood** [comment]
However, Javascript is a dynamic language, for all the implementations `unhandled rejection` is just a guess, you never know if an async error is handled at some point in the future . For example, no implementation can handle the code below correctly:

```js
var p = Promise.reject()

setTimeout(() => {
     p.catch(() => {})
}, 1e9)
```
Actually the vm needs to understand the meaning of your code to handle it correctly, which is apparently impossible at current AI tech.

So, the problem changes to make the guess warning less annoying. To suppress it as much as possible.

Your `p1` andy `p2` is just containers, they contains the same error value. Why we should waste cpu to log it twice?

**Comment by ysmood** [comment]
Another thing the spec doesn't mention is what is an `unhandled rejection` philosophically?

This code:

```js
p0 = Yaku.resolve().then(function () {
    abc()
})
p1 = p0.then(function () {})
p2 = p0.then(function () {})
p3 = p0.catch(function () {})
```
Apparently has a handler for the original rejection.

But on the other side, you could also say it doesn't have a handler for the inherent rejection. It really depends on your definition of `unhandled rejection`.

**Comment by rtsao** [comment]
> However, Javascript is a dynamic language, for all the implementations unhandled rejection is just a guess, you never know if an async error is handled at some point in the future.

Right, which is why both `unhandledrejection` `handledrejection` events are emitted. It's up to the user to reconcile the two. For example: https://googlechrome.github.io/samples/promise-rejection-events/index.html

**Comment by ysmood** [comment]
I prefer the `original rejection` as I mentioned, it's more intuitive.

**Comment by rtsao** [comment]
Fair enough, feel free to close this issue if you disagree.

However, my personal opinion is that it should conform to the spec rather than use some special snowflake logic on how these events operate.

**Comment by ysmood** [comment]
What spec do you mean? `unhandled rejection` is not a part of ES spec, Chrome is not a spec. For me it's a runtime decision.

**Comment by rtsao** [comment]
It's not codified in ECMAScript, (which only suggests a typical implementation:)

> A typical implementation of HostPromiseRejectionTracker might try to notify developers of unhandled rejections, while also being careful to notify them if such previous notifications are later invalidated by new handlers being attached.

However, I think browser `unhandledrejection` and `rejectionhandled` events are part of a codified browser spec (not just Chrome).

https://html.spec.whatwg.org/multipage/webappapis.html#unhandled-promise-rejections

https://github.com/w3c/web-platform-tests/tree/master/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections

**Comment by ysmood** [comment]
That why I said Chrome doesn't handle it improperly here: https://github.com/ysmood/yaku/blob/master/docs/debugHelperComparison.md#better-unhandled-error

If I think they are all right, why would I take time to optimize the behavior?

I hope my thoughts could help to evolve the spec 😁
