### ISSUE TITLE
Yaku.all is overridden by yaku/utils/all on yaku.brower.full.min.js version

### ISSUE THREAD

**Issue by banbanchs** [ysmood/yaku#47]
Reproduction:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
  <script src="path/to/yaku.browser.full.min.js"></script>
  <script>
    console.log(Yaku.all);
  </script>
</body>
</html>
```

`Yaku.all` expect is `Promise.all` but actually is [yaku.util.all](https://github.com/ysmood/yaku#alllimit-list)

https://github.com/ysmood/yaku/blob/master/src/browser.full.js#L8

**Comment by ysmood** [comment]
Actually, I'd like to remove file `browser.full.js`. Nowadays, people are more comfort with webpack and require.

**Comment by ysmood** [comment]
What do you think?

**Comment by banbanchs** [comment]
I just needed a simple Promise polyfill, I OK with it. Thanks anyway :)
