### ISSUE TITLE
Yaku's longStackTrace not so useful as bluebird's

### ISSUE THREAD

**Issue by kdepp** [ysmood/yaku#5]
check out the test case here: https://gist.github.com/kdepp/1d58214e989c9d4166f4

Both with the longStackTrace option on, bluebird gives me the exact exception point and all other calls when promises are resolved, while yaku only prints out the outmost 'then' and other useless function call.

Any thoughts on this?

**Comment by ysmood** [comment]
This should be an enhancement. I'll take time to optimize it.

**Comment by ysmood** [comment]
By the way, could you please simplify your test case? It's somehow too complex for others to reason about. I think most of the code of your test case is not necessary to issue the problem.

**Comment by kdepp** [comment]
sure, updated

**Comment by ysmood** [comment]
I think I found why. I only optimized the situation like this:

```coffeescript
new Promise (r, rr) ->
  a.b.c()   # error info will track to this line
```

The user rejected value should also be tracked, but I missed this case:

```coffeescript
new Promise (r, rr) ->
  rr()
```

**Comment by kdepp** [comment]
Maybe not that simple. Even with the untracked code exception, Yaku reports the previous event at the last 'then', not the exact line where the error was thrown.

check out this case: https://gist.github.com/kdepp/75a3f617ba82404b5a4b

previous event should be at L11, not L13

**Comment by ysmood** [comment]
You don't seem to use the latest version of Yaku.

**Comment by ysmood** [comment]
@kdepp I optimize the long stack trace. Now I think it's even better and simpler than Bluebird's.

For example: https://gist.github.com/ysmood/e7ebbb3a3487d66c96e8

Yaku will trace to the very first root Promise object (L8). But Bluebird won't, it only ends on (L10).

**Comment by ysmood** [comment]
@kdepp `v0.2.2` published. Please read the [Compare to Bluebird](https://github.com/ysmood/yaku/blob/master/docs/debugHelperComparison.md).
