### ISSUE TITLE
Bind to Angular 1.x digest?

### ISSUE THREAD

**Issue by lifenautjoe** [ysmood/yaku#50]
Bluebird provides the Promise.[setScheduler](https://github.com/petkaantonov/bluebird/blob/master/docs/docs/api/promise.setscheduler.md) method to bind with the angular digest cycle.

```js
// This will synchronize bluebird promise queue flushing with angulars queue flushing
// Angular is also now responsible for choosing the actual scheduler
Promise.setScheduler(function(fn) {
    $rootScope.$evalAsync(fn);
});
```

Can the same thing be achieved with Yaku?

**Comment by ysmood** [comment]
Do you mean https://github.com/ysmood/yaku#yakunexttick? You can try it.

**Comment by ysmood** [comment]
Yaku is more flexible than bluebird, such as you can set your own Symbol and Species. Bluebird cannot do that.

**Comment by lifenautjoe** [comment]
Sadly with no scheduler, I found no way to make it work.

**Comment by ysmood** [comment]
Are you sure you understand what I said? I said please check the `nextTick` API of Yaku, it's the same with Bluebird's setScheduler.

```js
const Promise = require('yaku')
Promise.nextTick = function(fn) {
    $rootScope.$evalAsync(fn);
}
```

**Comment by lifenautjoe** [comment]
Oh, no I didn't, thought you meant there was none with except the "Yaku is more flexible than Bluebird, except the async scheduler". Will try it out. Thanks.

**Comment by lifenautjoe** [comment]
Never came back to this. It works, thanks!
