### ISSUE TITLE
0.18.3 is broken if window.Promise is set to Yaku

### ISSUE THREAD

**Issue by kentor** [ysmood/yaku#53]
If i do something like this as a polyfill:

```js
window.Promise = require('yaku');
```

Then the recent change in 0.18.3 is broken: https://github.com/ysmood/yaku/commit/950101ff288cb3b0fc079736d8044a12492391f4

Shouldn't you capture `window.Promise` outside of the function in case it gets overridden?

**Comment by ysmood** [comment]
Well, that's a shame. I'll fix it.

**Comment by ysmood** [comment]
v0.18.4 published, a unit test also added for it 😂

**Comment by kentor** [comment]
nice. thanks! :D
