### ISSUE TITLE
"hash" util/helper request

### ISSUE THREAD

**Issue by 2hu12** [ysmood/yaku#58]
Could we add a [hash helper](https://github.com/tildeio/rsvp.js/blob/HEAD/README.md#hash-of-promises) like the `RSVP`, I think it's very convenient and useful? You think that is OK with you? Maybe I could implement it myself and make a PR.

**Comment by ysmood** [comment]
Good call, if you can make a PR, it would be appreciated.

**Comment by 2hu12** [comment]
Nice!
