### ISSUE TITLE
handled rejection can not be recognized

### ISSUE THREAD

**Issue by dracupid** [ysmood/yaku#6]
When I use `catch` or the second argument of `then` to handle a rejection, `Unhandled Rejection` is always shown.
```coffee
yaku = require 'yaku'
new yaku (resolve, reject) ->
    reject 1
.catch ->
```
the result is 
```
Unhandled Rejection: 1
```
I think this bug is introduced in v0.2.0

**Comment by ysmood** [comment]
@dracupid Yes, if you have seen the `dev` branch of this project, I'm already on this bug a week ago.
This week I will finally have time to fix it.

**Comment by ysmood** [comment]
The next version of Yaku will have much better long stack trace than Bluebird.
I will write an article to compare them.

**Comment by dracupid** [comment]
Good! Looking forward to it.

**Comment by ysmood** [comment]
@dracupid `v0.2.2` published. Please read the [Compare to Bluebird](https://github.com/ysmood/yaku/blob/master/docs/debugHelperComparison.md).
