### ISSUE TITLE
Support for Promise.allSetteled

### ISSUE THREAD

**Issue by allyraza** [ysmood/yaku#62]
hello, 

thank you for the nice library I am currently using http://polyfill.io which uses this as polyfill for `Promise`, but there is no support for `Promise.allSetteled` can you please consider this ?

-Thank you

**Comment by ysmood** [comment]
@allyraza Thanks for the report. Added the feature, and published v1.0.0, please check if it has bugs.

**Comment by allyraza** [comment]
@ysmood that was super quick you are amazing - THANK YOU! 🙏
