### ISSUE TITLE
long stack traces

### ISSUE THREAD

**Issue by ollym** [ysmood/yaku#7]
Are there any benchmarks which say what the trade-off is with using long stack traces?

Thanks

**Comment by ysmood** [comment]
@ollym The trade-off is very significant. I think there no reference value to have this benchmark. Don't enable it when your application is on production mode. Use it when you have to handle some complex async bugs.

**Comment by ollym** [comment]
@ysmood in a browser environment it's ok to enable it though?

**Comment by ysmood** [comment]
@ollym For browser, no need. See the [FQA](https://github.com/ysmood/yaku#faq) of readme. When you debug your site, for example, in Chrome, just enable the `async` flag, you will get the long stack trace automatically, and its user experience is much better than any promise lib.
