### ISSUE TITLE
utils aync strategy problem

### ISSUE THREAD

**Issue by zhulongzheng** [ysmood/yaku#8]
This issue is inspired by the [exercise](https://github.com/kolodny/exercises/tree/master/throttle-promises), as described in the test case of this exercise, when the throttled-promise handler get all it's tasks done, the `saveResults` should keep their order as they are the result of each one of `list`
``` coffeescript
async: (limit, list, saveResults, progress) ->
  ...
```

Also, I modify one existed test case of yours, to show the difference.
``` coffeescript
test 'async array', [1, 2, 3], ->
  list = [
    -> utils.sleep 90, 1
    -> utils.sleep 10, 2
    -> utils.sleep 10, 3
  ]

  utils.async 2, list
```
The old version will get `[2, 3, 1]` instead of `[1, 2, 3]`.

And there is a pull request. I hope myself get this right.

**Comment by ysmood** [comment]
Thanks!
